### PR TITLE
driver exoscale: clarify the image template name. [wip]

### PR DESCRIPTION
**Pull request by greut**
a dry-run PR to double check before sending it over.

### Proposed changes

It clarifies some aspects of the docker-machine exoscale driver usage. It wasn't super easy to guess the image name from the ones displayed in the UI.

### Related issues (optional)

TODO: open PR on docker/machine with the updated egoscale repo.

### CODE REVIEW

**Review by marcaurele — CHANGES_REQUESTED** [review]
I would add a comment on the username that needs to match the remote login policy of the selected image: coreOs, you must use `core` as the username otherwise the deploy won't work. Maybe simply add a third column to the table to state the `exoscale-ssh-user` corresponding to the template.

**Comment by greut** [comment]
:+1: that thing could be automagically done into the driver.

- `Ubuntu` ~> `ubuntu`
- `CoreOS`~> `core`
- _otherwise_ ~> `root`

But adding a little bit of text is always good.

**Comment by greut** [comment]
like that:

https://github.com/docker/machine/compare/master...exoscale:exoscale/upgrade

**Comment by marcaurele** [comment]
We have a rule set defined in the console to display the correct username (it's a bit more complicated due to version number), have a look at https://github.com/exoscale/console/blob/e3dd6301764cb94b30a8cfdc78e61c4158bded4a/tests/js/actions/templates.js#L17

I would keep the zone name in lower case, since typing it on the command line is easier if all is in small caps (or most of the arguments).

**Comment by greut** [comment]
https://github.com/exoscale/console/blob/e3dd6301764cb94b30a8cfdc78e61c4158bded4a/js/app/config.js#L216-L229

**Comment by greut** [comment]
> I would keep the zone name in lower case, since typing it on the command line is easier if all is in small caps (or most of the arguments).

It matches what is shown to the user. Everything goes/will go through a `ToLower()`; hence it doesn't matter much.

**Comment by marcaurele** [comment]
The console is the graphical part for better UI/reading. It would look a bit smallish on the portal if it was done in lowercase. I'm still in favor of having most of the terminal typing done in lowercase. The other drivers keep their variable default values in lowercase too (everything, even template names), check DO, Google, Amazon...

**Comment by greut** [comment]
Is it better?

https://github.com/exoscale/docker.github.io/blob/exoscale/imagename/machine/drivers/exoscale.md

**Review by marcaurele — APPROVED** [review]

**Comment by marcaurele** [comment]
yes

**Comment by greut** [comment]
I'll open it @docker once the egoscale and docker-machine PRs go through.

**Comment by marcaurele** [comment]
Ships them all together and add references in the PR comments, that will help get them merged

**Comment by greut** [comment]
https://github.com/docker/docker.github.io/pull/5487

**Pull request closed without merging**
